#!/bin/bash

DATE="$(date +'%d-%m-%y_%H:%M:%S')"
DIR="$HOME/Pictures/Screenshots"
PIC="$DIR/$DATE.png"

[ ! -d "$DIR" ] && mkdir -pv "$DIR"

abort() {
  notify-send -a "Screenshot info" -i dialog-error "Screenshot" "aborted"
  exit 1
}

notification() {
  NOTIFY=$(notify-send -A open=Open -A delete=Delete -a Screenshot -i "$PIC" "Copied to clipboard" "$PIC")
  if [[ $NOTIFY == "open" ]]; then
    feh $PIC
  elif [[ $NOTIFY == "delete" ]]; then
    rm -rf $PIC
  else
    exit 0
  fi
}

case "$1" in
full)
  grim "$PIC" || abort
  wl-copy <"$PIC"
  notification
  ;;
crop)
  grim -g "$(slurp -w 0)" "$PIC" || abort
  wl-copy <"$PIC"
  notification
  ;;
esac
